name: Behavioural Simulation Workflow with Verilator

on: [workflow_dispatch, workflow_call]

jobs:
  Run-Behavioural-Simulation-Verilator-Workflow:
    runs-on: ubuntu-24.04

    env:
      PROJ_NAME: "workflow_sandbox"

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          path: ${{ env.PROJ_NAME }}

      # Install Verilator prerequisite packages
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git help2man perl python3 make g++ libfl-dev zlib1g-dev ccache autoconf numactl perl-doc

      # Checkout Verilator
      - name: Checkout Verilator
        uses: actions/checkout@v7
        with:
          repository: verilator/verilator
          ref: v5.052 # Optional: Specify a tag/version, or remove this line for 'master'
          path: verilator

      # Compile Verilator
      - name: Compile Verilator
        run: |
          cd verilator
          autoconf
          ./configure --prefix=$HOME/verilator
          make -j$(nproc)
          make install

      # Adds verilator to PATH
      - name: Add Verilator to PATH
        run: |
          echo "$HOME/verilator/bin" >> $GITHUB_PATH

      # Sanity check Verilator version
      - name: Verify Verilator Version
        run: |
          verilator --version

      # Set Python up
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      # Get python packages
      - name: Install Python packages
        shell: bash
        run: pip install -r ${{ env.PROJ_NAME }}/tb/bin/requirements.txt

      # Run simulation
      - name: Run tests
        run: |
          cd ${{ env.PROJ_NAME }}/tb
          make clean SIM=verilator
          make SIM=verilator
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      # Collect results
      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.6
        with:
          paths: "${{ env.PROJ_NAME }}/tb/results.xml"

      # Upload simulation wave dump
      - name: Upload Waveform and Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: behavioural_test_results_verilator
          path: |
            ${{ env.PROJ_NAME }}/tb/dump.vcd
            ${{ env.PROJ_NAME }}/tb/dump.fst
            ${{ env.PROJ_NAME }}/tb/results.xml
