name: Gate Level Simulation Workflow with Verilator

on: [workflow_dispatch, workflow_call]

jobs:
  Run-Gate-Level-Simuation-Verilator-Workflow:
    runs-on: ubuntu-24.04

    env:
      VERILATOR_VERSION: "5.052"

    steps:

      # Download Librelane artifact
      - name: Download GDS artifact
        uses: actions/download-artifact@v8
        with:
          name: librelane-logs
          path: ~/librelane_logs_dir

      # Get PDK from github directly
      - name: Clone IHP PDK repo
        run: |
         git clone --branch dev --recurse-submodules https://github.com/IHP-GmbH/IHP-Open-PDK.git

      # Install prerequisite packages
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git help2man perl python3 make g++ libfl-dev zlib1g-dev ccache autoconf numactl perl-doc

      - name: Clone and compile Verilator
        run: |
          git clone --depth 1 --branch v${{ env.VERILATOR_VERSION }} https://github.com/verilator/verilator.git
          cd verilator
          autoconf
          ./configure --prefix=/home/runner/verilator-dist
          make -j$(nproc)
          make install

      - name: Add Verilator to PATH
        run: |
          echo "/home/runner/verilator-dist/bin" >> $GITHUB_PATH

      - name: Verify Verilator Version
        run: |
          verilator --version

      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v7

      # Set Python up
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      # Install required packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Copy gate level netlist
      - name : Copy Gate Level netlist from artifact
        shell: bash
        run: |
          find ~/librelane_logs_dir \
          -path "*/final/nl/i2c_slave.nl.v" \
          -type f \
          -exec cp {} tb/gate_level_netlist.v \;

      # Run simulation
      - name: Run Gate Level Simulation tests
        shell: bash
        run: |
          cd tb
          rm -f tb.vcd tb.fst results.xml
          make clean SIM=verilator
          make SIM=verilator GATES=yes
          # `make` will return success even if the tests fail, so check for failure in results.xml
          ! grep failure results.xml

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.6
        with:
          paths: tb/results.xml

      - name: Upload Waveform and Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
            name: gatelevel_test_results_verilator
            path: |
              tb/dump.vcd
              tb/dump.fst
              tb/results.xml
